# Generated by Django 5.2 on 2025-04-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
